# Generated by Django 5.1.7 on 2025-05-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_expires_at_teaseritem_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='category',
            field=models.CharField(choices=[('bags', 'Bags'), ('tops', 'Tops'), ('dress', 'Dress'), ('bottom', 'Bottom')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teaseritem',
            name='category',
            field=models.CharField(choices=[('bags', 'Bags'), ('tops', 'Tops'), ('dress', 'Dress'), ('bottom', 'Bottom')], max_length=10),
        ),
    ]
